### ISSUE TITLE
Channel plot has incorrect units 

### ISSUE THREAD

**Issue by RayStick** [physiopy/phys2bids#137] opened 2020-02-05 00:28 UTC
The channel plot has incorrect y-axis units, when using labchart text files as an input (trigger channel is second column). 

## Expected Behavior

When running:
`phys2bids -in Test_2minRest_trig_multifreq_header_no_comment.txt -info -chtrig 1`

I expect to get a channel plot with correct units associated with each channel (i.e. mmHg or volts)

## Actual Behavior

When running:
`phys2bids -in Test_2minRest_trig_multifreq_header_no_comment.txt -info -chtrig 1`

I get: 

```
> File extension is .txt
> Reading the file
> Reading infos
> File Test_2minRest_trig_multifreq_header_no_comment.txt contains:
> 
> 00. CO2; sampled at 1000.0 Hz
> 01. O2; sampled at 1000.0 Hz
> 02. Belt; sampled at 1000.0 Hz
> 03. Pulse; sampled at 1000.0 Hz
> saving channels plot at plot at Test_2minRest_trig_multifreq_header_no_comment.png
```

And this is the png:
![Test_2minRest_trig_multifreq_header_no_comment](https://user-images.githubusercontent.com/50215726/73799292-2c6b4b00-477b-11ea-9579-de5c45d9a446.png)

I have tried this on 3 other labchart text files (all the 1st col = time, 2nd col = trigger) and I get the same issue. 

## Steps to Reproduce the Problem

Run the command I have above. The text file can be found in phys2bids/tests/data

## Specifications

Python version: 3.7
phys2bids version: phys2bids v1.1.0-beta+236.g3a6fc72
Platform: MacOS

## Possible solution

I assume it might be something to do with the recent changes regarding lachart txt file compatibility for phys2bids, and something to do with 0 and 1 indexing in the code? But I am not sure.The units for plot 1 (trigger) should be plot2, and plot2 should be plot3 etc.

**Comment by vinferrer** [comment] 2020-02-05 09:27
let me close the PR #123 and i can start solving this and #138

**Comment by vinferrer** [comment] 2020-02-05 10:47
![image](https://user-images.githubusercontent.com/38909338/73835089-1c9c4700-480d-11ea-9f4a-d7eb049cd4fc.png)

I am running the same command with the PR #123 and this is the plot I get, Is this what you were expecting @RayStick ?

**Comment by vinferrer** [comment] 2020-02-05 10:49
Maybe I actually corrected this error in the PR #123 but the changes had not taken place because it need the final approval from @eurunuela and @smoia, let's wait for the merge and see if you can reproduce this result

**Comment by eurunuela** [comment] 2020-02-05 10:54
I have already accepted the PR. Up to @smoia now!

**Comment by smoia** [comment] 2020-02-05 11:39
Closed by #123

**Comment by vinferrer** [comment] 2020-02-05 11:40
The PR is finished, could you @RayStick  pull master and check everething is fine now?

**Comment by RayStick** [comment] 2020-02-05 15:17
Yes, works now!

**Closed** 2020-02-05 15:17 UTC
Labels: Bug
